name: Trigger auto deployment for kedsouza-ca2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/kedsouza-ca2-AutoDeployTrigger-23125d85-b449-4e71-9c59-72f4c6fb62d4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.KEDSOUZACA2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.KEDSOUZACA2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.KEDSOUZACA2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: kedsouza.azurecr.io
          registryUsername: ${{ secrets.KEDSOUZACA2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.KEDSOUZACA2_REGISTRY_PASSWORD }}
          containerAppName: kedsouza-ca2
          resourceGroup: Default-ActivityLogAlerts
          imageToBuild: kedsouza.azurecr.io/kedsouza-ca2:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


